#!/usr/bin/env bash
# submission-readiness-audit: bash wrapper that probes federation liveness,
# lists repo state, and outputs the audit skeleton (sections 1-3 pre-filled
# with disk-verified data).
#
# Usage:
#   bash run_readiness_audit.sh <repo-path> <submission-name> <deadline-YYYY-MM-DD>
#
# Example:
#   bash run_readiness_audit.sh /root/research/assetopsbench/arifos_a2b \
#       "A2B IJCAI 2026" 2026-08-01
#
# DITEMPA BUKAN DIBERI — the audit is forged, not given.

set -euo pipefail

REPO="${1:?usage: $0 <repo-path> <submission-name> <deadline>}"
NAME="${2:?usage: $0 <repo-path> <submission-name> <deadline>}"
DEADLINE="${3:?usage: $0 <repo-path> <submission-name> <deadline>}"
DATE=$(date +%Y-%m-%d)
DAYS_REMAINING=$(( ( $(date -d "$DEADLINE" +%s) - $(date +%s) ) / 86400 ))

cat <<HEADER
# ${NAME} — Submission Readiness Audit

**Date:** ${DATE}
**Author:** arifOS Federation · audit skeleton (pre-filled)
**Deadline:** ${DEADLINE} (**${DAYS_REMAINING} days remaining**)
**Scope:** ${NAME}
**Markers:** \`[OBS]\` disk-verified · \`[DER]\` derived · \`[INT]\` interpreted · \`[U]\` unknown

---

## 0. Federation Liveness Probe (pre-audit)

HEADER

echo '```'
for p in 8088 8081 3001 7072 18082 18083; do
  code=$(curl -sf -o /dev/null -w "%{http_code}" --max-time 3 "http://localhost:$p/health" 2>/dev/null || echo "000")
  echo "  port $p -> $code"
done
echo '```'
echo ""

cat <<HEADER

---

## 1. What You Have (Current State — Disk-Verified)

### 1.1 Repo \`${REPO}\`

HEADER

echo '```bash'
( cd "$REPO" 2>/dev/null && git log --oneline -5 2>/dev/null ) || echo "  (not a git repo)"
( cd "$REPO" 2>/dev/null && git status -sb 2>/dev/null ) || true
echo '```'
echo ""
echo "File count (excluding .git): \`$(find "$REPO" -type f -not -path '*/.git/*' 2>/dev/null | wc -l)\`"
echo ""

cat <<'HEADER'

### 1.2 Key files (auto-detected)

HEADER

for pattern in "reports/*SUBMISSION*" "reports/*EVAL*" "evals/*/eval_aggregate.json" \
               "docs/PROJECT_TRACKER.md" "docs/EVAL_NUMBERS.md" "README.md" \
               "harness/eval_harness.py" "notebooks/*.py"; do
  matches=$(find "$REPO" -path "*$pattern" -type f 2>/dev/null | head -5 || true)
  if [ -n "$matches" ]; then
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      lines=$(wc -l < "$f" 2>/dev/null || echo "?")
      size=$(stat -c%s "$f" 2>/dev/null || echo "?")
      echo "  - \`$f\` ($lines lines, $size bytes)"
    done <<< "$matches"
  fi
done

cat <<'HEADER'

### 1.3 Eval Results (auto-detected)

HEADER

if [ -d "$REPO/evals" ]; then
  for f in "$REPO"/evals/*/eval_aggregate.json; do
    [ -f "$f" ] || continue
    echo "#### $f"
    echo ""
    echo '```json'
    head -25 "$f"
    echo "...(truncated)..."
    echo '```'
    echo ""
  done
fi

cat <<'HEADER'

---

## 2-10. To be filled by the auditor

Run the 10-section structure from `references/a2b-ijcai-2026-audit-2026-07-03.md`:

2. What's Missing (Tier 1/2/3)
3. What's Chaos
4. What's Needed
5. Risk Matrix
6. 3-Option Recommendation
7. Critical Unknown
8. Day-by-Day Action Plan
9. What's Chaos (call it out)
10. Constitutional Receipt

---

*Skeleton generated by `scripts/run_readiness_audit.sh`.*
*DITEMPA BUKAN DIBERI.*
HEADER
