#!/bin/bash
# APEX Daily Pulse — Anti-Gödel anchor
#
# Cron schedule (recommended): 0 9 * * 1 (Mondays 09:00 MYT)
# i.e., weekly. Not daily. The pulse is meant to be rare, terse, and human-readable.
#
# What it does:
#   1. Pulls raw metrics from turn_outcomes (last 7 days).
#   2. Counts HOLD/SEAL/VOID by organ.
#   3. Counts prompt mutations in the last 7 days.
#   4. Writes raw data to a log file.
#   5. The 3-sentence pulse is generated by the LLM from this raw data,
#      posted to AAA Telegram, then sealed in VAULT999.
#
# Bound by: AAA_TRINITY_PROTOCOL.md, RECURSIVE_IMPROVEMENT_LOOP.md, DSG canon.
# Anti-Universe-25 rule: 3 sentences maximum. No debate. The pulse IS the answer.

set -e

# Paths
APEX_DIR="/root/AAA/agents"
PULSE_RAW="${APEX_DIR}/apex_pulse_raw.log"
PULSE_HUMAN="${APEX_DIR}/apex_pulse_human.log"
MUTATIONS_LOG="${APEX_DIR}/prompt_mutations.log"

# Time window: last 7 days
SINCE=$(date -u -d "7 days ago" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -v-7d +%Y-%m-%dT%H:%M:%SZ)
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Header
{
    echo "=========================================="
    echo "APEX WEEKLY PULSE — raw data"
    echo "Window: ${SINCE} → ${NOW}"
    echo "=========================================="
    echo ""
} > "${PULSE_RAW}"

# Metric 1: Turn outcomes by organ
# (assumes turn_outcomes is queryable via vault999-writer; if not, fallback to local log)
if command -v curl >/dev/null 2>&1; then
    echo "TURNS (last 7 days, by organ, by verdict):" >> "${PULSE_RAW}"
    # Placeholder: the actual implementation queries VAULT999 or the local store.
    # For now, write a stub the LLM can fill in if the store isn't ready.
    echo "  (data source not yet wired — see RECURSIVE_IMPROVEMENT_LOOP.md open items)" >> "${PULSE_RAW}"
    echo "" >> "${PULSE_RAW}"
fi

# Metric 2: Prompt mutations
if [ -f "${MUTATIONS_LOG}" ]; then
    MUTATION_COUNT=$(grep -c "\"action\":" "${MUTATIONS_LOG}" 2>/dev/null || echo "0")
    SEALED_COUNT=$(grep -c "\"action\": \"SEAL\"" "${MUTATIONS_LOG}" 2>/dev/null || echo "0")
    VOIDED_COUNT=$(grep -c "\"action\": \"VOID\"" "${MUTATIONS_LOG}" 2>/dev/null || echo "0")
    {
        echo "PROMPT MUTATIONS (all-time):"
        echo "  total:  ${MUTATION_COUNT}"
        echo "  sealed: ${SEALED_COUNT}"
        echo "  voided: ${VOIDED_COUNT}"
        echo ""
    } >> "${PULSE_RAW}"
fi

# Metric 3: Federation health (lightweight)
{
    echo "FEDERATION HEALTH (live):"
    for port_name in "8088:arifOS" "18081:arifosd" "18082:WEALTH" "18083:WELL" "8081:GEOX" "7071:A-FORGE" "3001:AAA"; do
        port="${port_name%%:*}"
        name="${port_name##*:}"
        status=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:${port}/health" 2>/dev/null || echo "DOWN")
        echo "  ${name} (${port}): ${status}"
    done
    echo ""
} >> "${PULSE_RAW}"

# Footer
{
    echo "=========================================="
    echo "NEXT: LLM reads this and emits a 3-sentence pulse to AAA Telegram."
    echo "Then seals in VAULT999."
    echo "=========================================="
} >> "${PULSE_RAW}"

# Display for cron-mail / log inspection
cat "${PULSE_RAW}"

# TODO (next session): wire the LLM step that consumes this raw data and
# emits a 3-sentence pulse. The LLM is the judge of the three sentences,
# not a script. The script's job is to gather data. The pulse is human-shaped.
# Exit cleanly
exit 0
