#!/usr/bin/env python3
"""GEOX Prospect Narrator — TokenRouter synthesis pipeline.
Takes geox_prospect JSON output → TokenRouter → narrative geological dossier.
Output: markdown dossier to /root/AAA/docs/prospects/ or stdout.
Usage: python3 /root/AAA/scripts/prospect_narrator.py [prospect_json_file]
       OR pipe: geox_prospect_output | python3 prospect_narrator.py --stdin
"""

import json, os, subprocess, sys
from datetime import datetime
from pathlib import Path

OUTPUT_DIR = "/root/AAA/docs/prospects"
TR_URL = "https://api.tokenrouter.com/v1/chat/completions"

def load_secrets():
    env_file = "/root/.secrets/vault.env"
    if os.path.exists(env_file):
        result = subprocess.run(["bash", "-c", f"set -a; . {env_file}; set +a; env"], capture_output=True, text=True)
        for line in result.stdout.split("\n"):
            if "=" in line:
                k, _, v = line.partition("=")
                os.environ[k] = v

def build_prompt(prospect_data):
    # Extract key fields from GEOX prospect output
    name = prospect_data.get("prospect_ref", prospect_data.get("name", "Unnamed Prospect"))
    basin = prospect_data.get("basin", prospect_data.get("basin_context", "Unknown Basin"))
    
    # Volumetrics
    vol = prospect_data.get("volumetrics", {})
    p50 = vol.get("p50_mmboe", vol.get("mean_mmboe", "?"))
    p10 = vol.get("p10_mmboe", "?")
    p90 = vol.get("p90_mmboe", "?")
    
    # Risk
    risk = prospect_data.get("risk", prospect_data.get("pos", {}))
    pos = risk.get("pos", risk.get("overall", "?"))
    
    # Economics
    econ = prospect_data.get("economics", prospect_data.get("emv", {}))
    emv = econ.get("emv_musd", econ.get("npv_musd", "?"))
    
    # Raw data dump
    raw = json.dumps(prospect_data, indent=2)[:4000]
    
    prompt = f"""You are a senior exploration geoscientist writing a prospect evaluation dossier.

PROSPECT DATA:
Name: {name}
Basin: {basin}
P50 Recoverable: {p50} MMBOE
P10-P90 Range: {p10} - {p90} MMBOE
Probability of Success: {pos}
EMV: {emv} MUSD

FULL DATA:
{raw}

Write a professional prospect dossier (4-6 paragraphs) covering:
1. Executive summary (2 sentences — is this worth drilling?)
2. Geological context (basin, play type, trapping mechanism)
3. Volumetrics and uncertainty (what drives the P10-P90 range?)
4. Risk assessment (key risks ranked by impact on POS)
5. Economics and recommendation

Rules:
- Professional geological language. This is for an experienced geoscientist.
- Be honest about uncertainty. If data is sparse, say so.
- Compare to basin analogs where possible.
- End with a clear recommendation: DRILL / APPRAISE / MORE DATA / DROP.
- Include "Key uncertainties:" as bullet points.

PROSPECT DOSSIER:"""
    return prompt, name

def call_tokenrouter(prompt):
    TR_KEY = os.getenv("TOKENROUTER_API_KEY", "")
    TR_MODEL = os.getenv("TOKENROUTER_MODEL", "deepseek/deepseek-v4-pro")
    if not TR_KEY:
        return "⚠️ TokenRouter API key not set."
    
    import urllib.request
    payload = json.dumps({
        "model": TR_MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 2000,
        "temperature": 0.4
    }).encode()
    
    req = urllib.request.Request(TR_URL, data=payload, headers={
        "Authorization": f"Bearer {TR_KEY}",
        "Content-Type": "application/json"
    })
    
    try:
        with urllib.request.urlopen(req, timeout=90) as resp:
            result = json.loads(resp.read())
            return result["choices"][0]["message"]["content"]
    except Exception as e:
        return f"⚠️ TokenRouter: {e}"

def main():
    load_secrets()
    
    # Read input
    if "--demo" in sys.argv:
        prospect_data = {
            "prospect_ref": "Alpha-1",
            "basin": "Malay Basin",
            "volumetrics": {"p10_mmboe": 85, "p50_mmboe": 45, "p90_mmboe": 15},
            "risk": {"pos": 0.32, "trap_seal": 0.7, "reservoir": 0.8, "source_charge": 0.9, "migration": 0.65},
            "economics": {"emv_musd": 42, "npv_musd": 120, "well_cost_musd": 25}
        }
    elif "--stdin" in sys.argv:
        raw = sys.stdin.read()
        prospect_data = json.loads(raw)
    elif len(sys.argv) > 1:
        with open(sys.argv[1]) as f:
            prospect_data = json.load(f)
    else:
        print("Usage: python3 prospect_narrator.py <prospect.json>")
        print("   or: cat prospect.json | python3 prospect_narrator.py --stdin")
        print("   or: python3 prospect_narrator.py --demo")
        sys.exit(1)
    
    prompt, name = build_prompt(prospect_data)
    dossier = call_tokenrouter(prompt)
    
    output = f"""# 🛢️ {name} — Prospect Dossier

> **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}
> **Pipeline:** GEOX data → TokenRouter (deepseek-v4-pro) → narrative dossier
> **Epistemic:** AI-SYNTHESIZED from GEOX data. Human review recommended before investment decisions.

---

{dossier}

---

*Generated by GEOX Prospect Narrator. Data source: GEOX organ (:8081). Synthesis: TokenRouter.*
"""
    
    if "--stdin" in sys.argv or len(sys.argv) > 1:
        print(output)
    else:
        Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
        out_path = f"{OUTPUT_DIR}/{name.replace(' ', '_')}.md"
        with open(out_path, "w") as f:
            f.write(output)
        print(f"✅ Dossier written to {out_path}")

if __name__ == "__main__":
    main()
