#!/usr/bin/env node
/**
 * jitu_token.js — JITU Token Creation & Validation
 * =================================================
 * JITU = Jaminan Integriti Tindakan Urus (Governed Action Integrity Guarantee)
 *
 * A JITU token is a signed proof that:
 *   1. A specific action was classified by the policy engine
 *   2. The classification was reviewed (auto or human)
 *   3. The approval is time-bounded (TTL)
 *   4. The token is bound to a specific tool + actor + payload hash
 *
 * Token format: jitu_<version>.<base64url(payload)>.<signature>
 *
 * Two token sources:
 *   - AUTO_JITU: Generated by the proxy for AUTO_PASS actions (audit-only)
 *   - SOVEREIGN_JITU: Generated by Arif (888_ACK) for JITU_REQUIRED actions
 *
 * DITEMPA BUKAN DIBERI — Forged, Not Given.
 */

'use strict';

const crypto = require('crypto');

// ── Configuration ─────────────────────────────────────────────────────────

const JITU_SECRET = process.env.JITU_SECRET || crypto.randomBytes(32).toString('hex');
const DEFAULT_TTL_SECONDS = 300; // 5 minutes
const SOVEREIGN_TTL_SECONDS = 3600; // 1 hour for sovereign tokens

// ── Token Creation ────────────────────────────────────────────────────────

/**
 * Create a JITU token.
 *
 * @param {object} params
 * @param {string} params.tool_name — tool being authorized
 * @param {string} params.actor_id — who is calling
 * @param {string} params.payload_hash — SHA-256 of the tool arguments
 * @param {string} params.approval_type — 'AUTO_JITU' | 'SOVEREIGN_JITU'
 * @param {number} [params.ttl_seconds] — token lifetime
 * @param {string} [params.sovereign_id] — who approved (for SOVEREIGN_JITU)
 * @param {string} [params.seal_id] — linked VAULT999 seal ID
 * @returns {{ token: string, expires_at: string, payload: object }}
 */
function createJituToken({
  tool_name,
  actor_id,
  payload_hash,
  approval_type = 'AUTO_JITU',
  ttl_seconds,
  sovereign_id,
  seal_id,
}) {
  const now = new Date();
  const ttl = ttl_seconds || (approval_type === 'SOVEREIGN_JITU' ? SOVEREIGN_TTL_SECONDS : DEFAULT_TTL_SECONDS);
  const expires_at = new Date(now.getTime() + ttl * 1000);

  const payload = {
    v: 1,
    tool: tool_name,
    actor: actor_id,
    hash: payload_hash,
    type: approval_type,
    iss: approval_type === 'SOVEREIGN_JITU' ? (sovereign_id || '888') : 'safety-proxy',
    iat: now.toISOString(),
    exp: expires_at.toISOString(),
    seal: seal_id || null,
    nonce: crypto.randomBytes(8).toString('hex'),
  };

  const payloadB64 = Buffer.from(JSON.stringify(payload)).toString('base64url');
  const signature = crypto
    .createHmac('sha256', JITU_SECRET)
    .update(payloadB64)
    .digest('base64url');

  const token = `jitu_v1.${payloadB64}.${signature}`;

  return { token, expires_at: expires_at.toISOString(), payload };
}

// ── Token Validation ──────────────────────────────────────────────────────

/**
 * Validate a JITU token.
 *
 * @param {string} token — the JITU token string
 * @param {object} [context] — optional context for binding check
 * @param {string} [context.tool_name] — expected tool name
 * @param {string} [context.actor_id] — expected actor
 * @param {string} [context.payload_hash] — expected payload hash
 * @returns {{ valid: boolean, payload: object|null, error: string|null }}
 */
function validateJituToken(token, context) {
  if (!token || typeof token !== 'string') {
    return { valid: false, payload: null, error: 'MISSING_TOKEN' };
  }

  // Parse token
  const parts = token.split('.');
  if (parts.length !== 3 || parts[0] !== 'jitu_v1') {
    return { valid: false, payload: null, error: 'MALFORMED_TOKEN' };
  }

  const [, payloadB64, signature] = parts;

  // Verify signature (timing-safe)
  const expectedSig = crypto
    .createHmac('sha256', JITU_SECRET)
    .update(payloadB64)
    .digest('base64url');

  const sigBuf = Buffer.from(signature);
  const expBuf = Buffer.from(expectedSig);
  if (sigBuf.length !== expBuf.length || !crypto.timingSafeEqual(sigBuf, expBuf)) {
    return { valid: false, payload: null, error: 'INVALID_SIGNATURE' };
  }

  // Decode payload
  let payload;
  try {
    payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf-8'));
  } catch {
    return { valid: false, payload: null, error: 'DECODE_FAILED' };
  }

  // Check expiry
  if (payload.exp && new Date(payload.exp) < new Date()) {
    return { valid: false, payload, error: 'TOKEN_EXPIRED' };
  }

  // Context binding check (if provided)
  if (context) {
    if (context.tool_name && payload.tool !== context.tool_name) {
      return { valid: false, payload, error: 'TOOL_MISMATCH' };
    }
    if (context.actor_id && payload.actor !== context.actor_id) {
      return { valid: false, payload, error: 'ACTOR_MISMATCH' };
    }
    if (context.payload_hash && payload.hash !== context.payload_hash) {
      return { valid: false, payload, error: 'PAYLOAD_MISMATCH' };
    }
  }

  return { valid: true, payload, error: null };
}

// ── Payload Hash ──────────────────────────────────────────────────────────

/**
 * Compute a deterministic hash of tool arguments for token binding.
 */
function hashPayload(args) {
  if (!args) return 'sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'; // empty
  const canonical = JSON.stringify(args, Object.keys(args).sort());
  return 'sha256:' + crypto.createHash('sha256').update(canonical).digest('hex');
}

// ── Exports ───────────────────────────────────────────────────────────────

module.exports = {
  createJituToken,
  validateJituToken,
  hashPayload,
  DEFAULT_TTL_SECONDS,
  SOVEREIGN_TTL_SECONDS,
};
