#!/usr/bin/env python3
"""
Acceptance test runner for video-evidence-packager v0.

Tests all 10 acceptance criteria from the specification.
Requires fixtures generated by generate_fixtures.py.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile

# Add parent to path for import
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from packager import packager, sha256_file

FIXTURES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")
TOOLS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

passed = 0
failed = 0
results = []


def test(name, condition, detail=""):
    global passed, failed
    if condition:
        passed += 1
        results.append(("PASS", name, detail))
        print(f"  PASS  {name}")
    else:
        failed += 1
        results.append(("FAIL", name, detail))
        print(f"  FAIL  {name} — {detail}")


def run_tests():
    global passed, failed

    short_video = os.path.join(FIXTURES_DIR, "short_5s.mp4")
    corrupt_file = os.path.join(FIXTURES_DIR, "corrupt.xyz")
    empty_file = os.path.join(FIXTURES_DIR, "empty.mp4")

    # Ensure fixtures exist
    if not os.path.exists(short_video):
        print("Generating fixtures...")
        subprocess.run([sys.executable, os.path.join(FIXTURES_DIR, "..", "tests", "generate_fixtures.py")],
                       check=True, cwd=TOOLS_DIR)

    print("\n=== video-evidence-packager v0 Acceptance Tests ===\n")

    # --- TEST SUITE 1: Successful extraction ---
    print("--- Suite 1: Successful extraction (short_5s.mp4) ---")
    with tempfile.TemporaryDirectory() as tmpdir:
        out1 = os.path.join(tmpdir, "run1")
        r1 = packager(short_video, output_dir=out1)

        # 1. Deterministic: run again, compare timestamps
        out1b = os.path.join(tmpdir, "run1b")
        r1b = packager(short_video, output_dir=out1b)

        with open(os.path.join(out1, "keyframes.json")) as f:
            kf1 = json.load(f)
        with open(os.path.join(out1b, "keyframes.json")) as f:
            kf1b = json.load(f)

        timestamps_1 = [fr["timestamp_seconds"] for fr in kf1["frames"]]
        timestamps_1b = [fr["timestamp_seconds"] for fr in kf1b["frames"]]

        test("1. Deterministic: same timestamps on re-run",
             timestamps_1 == timestamps_1b,
             f"{timestamps_1} vs {timestamps_1b}")

        # 2. SHA-256 on every artifact
        all_hashed = all("sha256" in fr and len(fr["sha256"]) == 64 for fr in kf1["frames"])
        test("2. Every artifact has SHA-256", all_hashed)

        # 3. Exact timestamps relative to source
        all_have_ts = all("timestamp_seconds" in fr and "timestamp_hms" in fr for fr in kf1["frames"])
        test("3. Every frame has exact timestamp", all_have_ts)

        # 4. Frame count <= cap
        test("4. Frame count <= max_frames (24)",
             kf1["total_frames"] <= 24,
             f"got {kf1['total_frames']}")

        # 6. No inferred content in evidence segments
        with open(os.path.join(out1, "evidence-segments.jsonl")) as f:
            segments = [json.loads(line) for line in f if line.strip()]
        no_inferred = all(
            seg.get("text") is None and
            seg.get("confidence") == 1.0 and
            seg.get("status") == "observed"
            for seg in segments
        )
        test("6. No inferred captions/objects/emotions", no_inferred)

        # 7. Manifest structure (basic validation)
        yaml_path = os.path.join(out1, "video_asset.yaml")
        with open(yaml_path) as f:
            yaml_content = f.read()
        has_video_asset_in_yaml = "video_asset:" in yaml_content
        has_sampling_in_yaml = "sampling:" in yaml_content
        yaml_exists = os.path.exists(yaml_path)
        test("7. Manifest structure valid",
             has_video_asset_in_yaml and has_sampling_in_yaml and yaml_exists)

        # 8. No network calls (receipt confirms external_calls=0)
        test("8. No external network calls",
             r1.get("external_calls") == 0,
             f"external_calls={r1.get('external_calls')}")

        # 9. Input not modified
        original_hash = sha256_file(short_video)
        test("9. Input media not modified",
             original_hash == sha256_file(short_video))

        # Receipt is success
        test("Receipt status = success", r1.get("status") == "success")

        # Keyframes exist on disk
        kf_dir = os.path.join(out1, "keyframes")
        kf_files = os.listdir(kf_dir) if os.path.exists(kf_dir) else []
        test("Keyframe files written", len(kf_files) > 0,
             f"found {len(kf_files)} files")

    # --- TEST SUITE 2: Failure handling ---
    print("\n--- Suite 2: Failure handling ---")

    # 5a. Corrupt file -> structured failure receipt
    with tempfile.TemporaryDirectory() as tmpdir:
        out_corrupt = os.path.join(tmpdir, "corrupt")
        r_corrupt = packager(corrupt_file, output_dir=out_corrupt)
        test("5a. Corrupt file -> structured failure receipt",
             r_corrupt.get("status") == "failed",
             f"status={r_corrupt.get('status')}")
        test("5a. Failure has error_class",
             "error_class" in r_corrupt,
             f"keys={list(r_corrupt.keys())}")
        # Verify receipt.json exists
        test("5a. Failure receipt.json written",
             os.path.exists(os.path.join(out_corrupt, "receipt.json")))

    # 5b. Empty file -> structured failure receipt
    with tempfile.TemporaryDirectory() as tmpdir:
        out_empty = os.path.join(tmpdir, "empty")
        r_empty = packager(empty_file, output_dir=out_empty)
        test("5b. Empty file -> structured failure receipt",
             r_empty.get("status") == "failed",
             f"status={r_empty.get('status')}")

    # 5c. Non-existent file -> structured failure receipt
    with tempfile.TemporaryDirectory() as tmpdir:
        out_missing = os.path.join(tmpdir, "missing")
        r_missing = packager("/nonexistent/video.mp4", output_dir=out_missing)
        test("5c. Missing file -> structured failure receipt",
             r_missing.get("status") == "failed",
             f"status={r_missing.get('status')}")

    # --- TEST SUITE 3: Edge cases ---
    print("\n--- Suite 3: Edge cases ---")

    # Custom interval
    with tempfile.TemporaryDirectory() as tmpdir:
        out_custom = os.path.join(tmpdir, "custom")
        r_custom = packager(short_video, interval=2.0, max_frames=3, output_dir=out_custom)
        with open(os.path.join(out_custom, "keyframes.json")) as f:
            kf_custom = json.load(f)
        test("Custom interval (2s, max 3): respects cap",
             kf_custom["total_frames"] <= 3,
             f"got {kf_custom['total_frames']}")
        test("Custom interval: timestamps spaced ~2s",
             len(kf_custom["frames"]) < 2 or
             kf_custom["frames"][1]["timestamp_seconds"] - kf_custom["frames"][0]["timestamp_seconds"] >= 1.9,
             f"gap={kf_custom['frames'][1]['timestamp_seconds'] - kf_custom['frames'][0]['timestamp_seconds'] if len(kf_custom['frames']) >= 2 else 'N/A'}")

    # Canonical URL propagation
    with tempfile.TemporaryDirectory() as tmpdir:
        out_url = os.path.join(tmpdir, "url")
        r_url = packager(short_video, canonical_url="https://www.youtube.com/watch?v=test123",
                         output_dir=out_url)
        with open(os.path.join(out_url, "keyframes.json")) as f:
            kf_url = json.load(f)
        with open(os.path.join(out_url, "evidence-segments.jsonl")) as f:
            segs_url = [json.loads(line) for line in f if line.strip()]
        url_propagated = all(
            seg.get("provenance_url", "").startswith("https://www.youtube.com")
            for seg in segs_url
        ) if segs_url else False
        test("Canonical URL propagated to evidence segments", url_propagated)

    # --- Summary ---
    print(f"\n=== Results: {passed} passed, {failed} failed ===\n")
    if failed > 0:
        print("FAILURES:")
        for status, name, detail in results:
            if status == "FAIL":
                print(f"  - {name}: {detail}")
        sys.exit(1)
    else:
        print("ALL TESTS PASSED")
        sys.exit(0)


if __name__ == "__main__":
    run_tests()
